// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy0U1TeJn5MR5qur4zcIgF9kcNssAVnuU',
    appId: '1:459669186229:android:028bb3c5e66bcb383c80fc',
    messagingSenderId: '459669186229',
    projectId: 'sekolah1-e6a6f',
    databaseURL: 'https://sekolah1-e6a6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sekolah1-e6a6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB86rg7NxkYt3posXrw3xZUED5vVkC5USI',
    appId: '1:459669186229:ios:a35fd330c922fd803c80fc',
    messagingSenderId: '459669186229',
    projectId: 'sekolah1-e6a6f',
    databaseURL: 'https://sekolah1-e6a6f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sekolah1-e6a6f.firebasestorage.app',
    iosBundleId: 'com.banasari.secondProject',
  );

}